# Implement all the services that are going to be tested in Integration tests
# You must make them public to be accessible through the container

services:
    App\Infrastructure\Messaging\Bus\MessengerEventBus:
        public: true
        arguments:
            - '@messenger.routable_message_bus'

    App\Infrastructure\Persistence\Doctrine\Client\PostgresClientRepository:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    App\Infrastructure\Persistence\Doctrine\Order\PostgresOrderRepository:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
